name: 'Download an Encrypted Build Artifact'
description: 'Download encrypted build artifact previously uploaded in a workflow by upload-encrypted-artifact action. Supports KMS.'
author: 'benjefferies'
branding:
  icon: 'unlock'
  color: 'gray-dark'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  kms-key-id:
    description: 'KMS key ID ARN used to decrypt the artifact'
    required: false
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node16'
  main: 'dist/index.js'
